### PR TITLE
Add Dockerfile for LSU CRC Coastal Model Repository

### PR DESCRIPTION
**Pull request by mdpiper**
Adding @mcflugen and @jtao.

I've added the Dockerfile used by @jtao to include HydroTrend in the CMR for use in Simulocean. Let's use the comments to discuss if any changes need to be made.

### CODE REVIEW

**Comment by jtao** [comment]
Thanks! I will make changes accordingly on docker hub to link it to this repo.

**Comment by mdpiper** [comment]
You're welcome, Jian! Let us know if we need to make any modifications to the Dockerfile.

**Comment by jtao** [comment]
We just tried and it seems that docker hub requires mutual permission between the docker account and github account to enable an automatic rebuild. It was not as simple as pointing to a public dockerfile. On docker hub, We won't be able to see this particular dockerfile as we don't own the this account or not in the same github organization. 

Currently, we are trying something else. Will keep you all updated if it works.

**Comment by mdpiper** [comment]
A thought (and I not sure this will help): we could use [csdms-contrib/hydrotrend](https://github.com/csdms-contrib/hydrotrend) instead of [kettner/hydrotrend](https://github.com/kettner/hydrotrend). CSDMS owns the **csdms-contrib** organization, and so we could open the permissions to Docker for this repository, instead of opening permissions to Albert's personal repository.

**Comment by kettner** [comment]
works for me
A.

On Tue, Mar 29, 2016 at 4:22 PM, Mark Piper notifications@github.com
wrote:

> A thought (and I not sure this will help): we could use
> csdms-contrib/hydrotrend https://github.com/csdms-contrib/hydrotrend
> instead of kettner/hydrotrend https://github.com/kettner/hydrotrend.
> CSDMS owns the _csdms-contrib_ organization, and so we could open the
> permissions to Docker for this repository, instead of opening permissions
> to Albert's personal repository.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/kettner/hydrotrend/pull/1#issuecomment-203137335

## 

Albert J. Kettner, Ph.D.
Research Scientist
CSDMS, INSTAAR, Univ. of Colorado
http://csdms.colorado.edu

Co-Director Dartmouth Flood Observatory
http://floodobservatory.colorado.edu/

P.O.Box 545
Boulder, CO, 80309, USA
Ph:+1-303-735-5486; Fax: +1-303-492-6388
http://instaar.colorado.edu/people/albert-j-kettner/

**Comment by mdpiper** [comment]
Alright, I've synced csdms-contrib/hydrotrend with kettner/hydrotrend and added the Docker service.

@jtao: Would you please try using https://github.com/csdms-contrib/hydrotrend instead of Albert's version?

**Comment by jtao** [comment]
Unfortunately, I still don't see the csdms repo when I tried to create a automatic rebuild. I think Docker requires that the github account must have certain permission level to the github repo to link to the Docker hub repo. Actually from the perspective of application deployment, it might be better to keep the source code as it is and deal with Docker related stuff separately. A separate repo might not be that bad. With all that said, I would still encourage you to create an automatic rebuild with your acount on Docker hub and try things out.

**Pull request merged**
